title: CACC UFFS
email: cacomputacaouffs@gmail.com.br
description: >- # this means to ignore newlines until "baseurl:"
    Canal de comunicação oficial do centro acadêmico do curso de ciência da computação da Universidade Federal Fronteira Sul de Chapecó/SC.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: Computacao_UFFS
github_username:  caccuffs

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /
 - title: O Curso
   url: /curso
 - title: F.A.Q.
   url: /faq
 - title: Sobre
   url: /sobre
 - title: Contato
   url: /contato
